var perguntasT1=[];
perguntasT1.push(['Onde será que deve chover menos de 30mm?','001','Olinda','Ipojuca']);
perguntasT1.push(['Quem tem mais chances de chover menos de 30mm?','002','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT1.push(['Quem tem mais chances de chover menos 50mm?','003','Escada','Floresta','Petrolina']);
perguntasT1.push(['Onde será que deve chover menos de 50mm?','004','Gravatá','Pombos']);
perguntasT1.push(['Quem tem mais chances de chover menos de 40mm?','005','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT1.push(['Quem tem mais chances de chover menos 60mm?','006','Escada','Floresta','Petrolina']);
perguntasT1.push(['Recife deve chover menos de 70mm?','007','Arcoverde','Triunfo']);
perguntasT1.push(['Quem tem mais chances de chover menos de 50mm?','008','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT1.push(['Quem tem mais chances de chover menos 60mm?','009','Escada','Floresta','Petrolina']);
perguntasT1.push(['Quem tem mais chances de chover menos 70mm?','010','Amaraji','Limoeiro','Moreno']);

var perguntasT2=[];
perguntasT2.push(['Onde será que deve chover menos de 30mm?','001','Olinda','Ipojuca']);
perguntasT2.push(['Quem tem mais chances de chover menos de 30mm?','002','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT2.push(['Quem tem mais chances de chover menos 50mm?','003','Escada','Floresta','Petrolina']);
perguntasT2.push(['Onde será que deve chover menos de 50mm?','004','Gravatá','Pombos']);
perguntasT2.push(['Quem tem mais chances de chover menos de 40mm?','005','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT2.push(['Quem tem mais chances de chover menos 60mm?','006','Escada','Floresta','Petrolina']);
perguntasT2.push(['Recife deve chover menos de 70mm?','007','Arcoverde','Triunfo']);
perguntasT2.push(['Quem tem mais chances de chover menos de 50mm?','008','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT2.push(['Quem tem mais chances de chover menos 60mm?','009','Escada','Floresta','Petrolina']);
perguntasT2.push(['Quem tem mais chances de chover menos 70mm?','010','Amaraji','Limoeiro','Moreno']);

var perguntasT3=[];
perguntasT3.push(['Onde será que deve chover menos de 30mm?','001','Olinda','Ipojuca']);
perguntasT3.push(['Quem tem mais chances de chover menos de 30mm?','002','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT3.push(['Quem tem mais chances de chover menos 50mm?','003','Escada','Floresta','Petrolina']);
perguntasT3.push(['Onde será que deve chover menos de 50mm?','004','Gravatá','Pombos']);
perguntasT3.push(['Quem tem mais chances de chover menos de 40mm?','005','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT3.push(['Quem tem mais chances de chover menos 60mm?','006','Escada','Floresta','Petrolina']);
perguntasT3.push(['Recife deve chover menos de 70mm?','007','Arcoverde','Triunfo']);
perguntasT3.push(['Quem tem mais chances de chover menos de 50mm?','008','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT3.push(['Quem tem mais chances de chover menos 60mm?','009','Escada','Floresta','Petrolina']);
perguntasT3.push(['Quem tem mais chances de chover menos 70mm?','010','Amaraji','Limoeiro','Moreno']);

var perguntasT4=[];
perguntasT4.push(['Onde será que deve chover menos de 30mm?','001','Olinda','Ipojuca']);
perguntasT4.push(['Quem tem mais chances de chover menos de 30mm?','002','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT4.push(['Quem tem mais chances de chover menos 50mm?','003','Escada','Floresta','Petrolina']);
perguntasT4.push(['Onde será que deve chover menos de 50mm?','004','Gravatá','Pombos']);
perguntasT4.push(['Quem tem mais chances de chover menos de 40mm?','005','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT4.push(['Quem tem mais chances de chover menos 60mm?','006','Escada','Floresta','Petrolina']);
perguntasT4.push(['Recife deve chover menos de 70mm?','007','Arcoverde','Triunfo']);
perguntasT4.push(['Quem tem mais chances de chover menos de 50mm?','008','Recife','Vitória de Santo Antão','Cabo de Santo Agostinho','Caruaru']);
perguntasT4.push(['Quem tem mais chances de chover menos 60mm?','009','Escada','Floresta','Petrolina']);
perguntasT4.push(['Quem tem mais chances de chover menos 70mm?','010','Amaraji','Limoeiro','Moreno']);